### ISSUE TITLE
regarding missing package 

### ISSUE THREAD

**Issue by dDua** [andreasvlachos/arow_csc#1]
Hi Andreas,

I was trying out your code. I couldn't find the implementation for _mycollections  and mydouble 

from _mycollections import mydefaultdict
from mydouble import mydouble, counts

Could you please let me know how to resolve it.

Thanks,
Dheeru

**Comment by andreasvlachos** [comment]
Hi Dheeru,

The libraries need to be downloaded from here (just checked the link and it works):
http://acl.cs.qc.edu/~lhuang/software/hvector-1.0.tar.bz

I am mentioning it in the README. Let me know if you have any problems with it.

Cheers,
Andreas

**Comment by dhruvghulati** [comment]
I had the same issue - please could you update the README?

**Comment by dhruvghulati** [comment]
Ignore, found it!
