### ISSUE TITLE
Structure of feature vector for a words example

### ISSUE THREAD

**Issue by dhruvghulati-zz** [andreasvlachos/arow_csc#7]
I am setting up the `Instance(featureVector, costDict)` for each training instance, and want to ensure my format is right for a bag of words. 

For each sentence, the `featureID` sum just goes up to the words in the sentence (e.g. 15, 18, 10). i.e. they are not global feature IDs that identify the word as unique among the training population. In addition, I am ensuring the `featureVal` are converted to unique numbers instead of being words, as in a sentence I want to sure the `featureVal` match if the word is the same.

An example of a sentence and the code to print it is:

```

featureList = featureList.split()


for featureID,featureVal in enumerate(featureList):
        print "featureID is",featureID
        print "featureVal is ",featureVal
        print "Encoded feature value is", id(intern(str(featureVal.encode("utf-8"))))
        featureVector[featureID] = float(id(intern(str(featureVal.encode("utf-8")))))

return Instance(featureVector, costDict)

Feature list is [u'guinea', u'bissau', u'compared', u'countriesthe', u'population', u'density', u'guinea', u'bissau', u'similar', u'iran', u'afghanistan', u'cameroon', u'panama', u'montenegro', u'guinea', u'belarus', u'palau', u'location_slot', u'south', u'africa', u'respective', u'population', u'density', u'lrb', u'capita', u'per', u'square', u'kilometer', u'rrb', u'global', u'rank', u'number_slot', u'years', u'growthguinea', u'bissau', u'population', u'density', u'positive', u'growth', u'lrb', u'rrb', u'last', u'years', u'lrb', u'rrb', u'LOCATION_SLOT~-appos+LOCATION~-prep_of', u'LOCATION~-prep_of+that~-prep_to', u'that~-prep_to+similar~prep_with', u'similar~prep_with+density~prep_of', u'density~prep_of+NUMBER~appos', u'NUMBER~appos+NUMBER~amod', u'NUMBER~amod+NUMBER_SLOT']
featureID is 0
featureVal is  guinea
Encoded feature value is 4569583120.0
featureID is 1
featureVal is  bissau
Encoded feature value is 4569581632.0
featureID is 2
featureVal is  compared
Encoded feature value is 4569583120.0
featureID is 3
featureVal is  countriesthe
Encoded feature value is 4567944360.0
featureID is 4
featureVal is  population
Encoded feature value is 4347153072.0
featureID is 5
featureVal is  density
Encoded feature value is 4455561472.0
featureID is 6
featureVal is  guinea
Encoded feature value is 4569581632.0
featureID is 7
featureVal is  bissau
Encoded feature value is 4569583120.0
featureID is 8
featureVal is  similar
Encoded feature value is 4496118144.0
featureID is 9
featureVal is  iran
Encoded feature value is 4569583120.0
featureID is 10
featureVal is  afghanistan
Encoded feature value is 4569581632.0
featureID is 11
featureVal is  cameroon
Encoded feature value is 4569583120.0
featureID is 12
featureVal is  panama
Encoded feature value is 4569581632.0
featureID is 13
featureVal is  montenegro
Encoded feature value is 4569583120.0
featureID is 14
featureVal is  guinea
Encoded feature value is 4569581632.0
featureID is 15
featureVal is  belarus
Encoded feature value is 4569583120.0
featureID is 16
featureVal is  palau
Encoded feature value is 4569581632.0
featureID is 17
featureVal is  location_slot
Encoded feature value is 4567944360.0
featureID is 18
featureVal is  south
Encoded feature value is 4569583120.0
featureID is 19
featureVal is  africa
Encoded feature value is 4569581632.0
featureID is 20
featureVal is  respective
Encoded feature value is 4569583120.0
featureID is 21
featureVal is  population
Encoded feature value is 4347153072.0
featureID is 22
featureVal is  density
Encoded feature value is 4455561472.0
featureID is 23
featureVal is  lrb
Encoded feature value is 4537993216.0
featureID is 24
featureVal is  capita
Encoded feature value is 4569581632.0
featureID is 25
featureVal is  per
Encoded feature value is 4455914152.0
featureID is 26
featureVal is  square
Encoded feature value is 4347127296.0
featureID is 27
featureVal is  kilometer
Encoded feature value is 4569581632.0
featureID is 28
featureVal is  rrb
Encoded feature value is 4537993216.0
featureID is 29
featureVal is  global
Encoded feature value is 4346597072.0
featureID is 30
featureVal is  rank
Encoded feature value is 4346629984.0
featureID is 31
featureVal is  number_slot
Encoded feature value is 4569583120.0
featureID is 32
featureVal is  years
Encoded feature value is 4569581632.0
featureID is 33
featureVal is  growthguinea
Encoded feature value is 4567944360.0
featureID is 34
featureVal is  bissau
Encoded feature value is 4569583120.0
featureID is 35
featureVal is  population
Encoded feature value is 4347153072.0
featureID is 36
featureVal is  density
Encoded feature value is 4455561472.0
featureID is 37
featureVal is  positive
Encoded feature value is 4514096160.0
featureID is 38
featureVal is  growth
Encoded feature value is 4569583120.0
featureID is 39
featureVal is  lrb
Encoded feature value is 4537993216.0
featureID is 40
featureVal is  rrb
Encoded feature value is 4537993216.0
featureID is 41
featureVal is  last
Encoded feature value is 4346568112.0
featureID is 42
featureVal is  years
Encoded feature value is 4569583120.0
featureID is 43
featureVal is  lrb
Encoded feature value is 4537993216.0
featureID is 44
featureVal is  rrb
Encoded feature value is 4537993216.0
featureID is 45
featureVal is  LOCATION_SLOT~-appos+LOCATION~-prep_of
Encoded feature value is 4538026784.0
featureID is 46
featureVal is  LOCATION~-prep_of+that~-prep_to
Encoded feature value is 6043251168.0
featureID is 47
featureVal is  that~-prep_to+similar~prep_with
Encoded feature value is 6043251168.0
featureID is 48
featureVal is  similar~prep_with+density~prep_of
Encoded feature value is 6043251168.0
featureID is 49
featureVal is  density~prep_of+NUMBER~appos
Encoded feature value is 6043251168.0
featureID is 50
featureVal is  NUMBER~appos+NUMBER~amod
Encoded feature value is 6043247024.0
featureID is 51
featureVal is  NUMBER~amod+NUMBER_SLOT
Encoded feature value is 6043247024.0
```
1. The encoded feature value isn't working even though I couldn't find any other way to assign a unique ID to a string (e.g. `similar~prep_with+density~prep_of` has the same encoded feature value as 
   `density~prep_of+NUMBER~appos`). **EDIT** I have worked out a way to do this on a local basis (so if same words on a sentence, then the ID is locally unique - http://stackoverflow.com/questions/39316897/cannot-get-unique-ids-for-a-string-python2-7#39317181)
2. Do I even need to encode the feature value, or can I just leave it as a string without using `id(intern(string)))` on it?
3. Do you need to have globally unique feature ID and feature values i.e. if "Spain" appears in one sentence, should it have feature ID = 2543, and another sentence keep that same featureID and featureValue?

Note, the test example you give has:

```
 dataset = ["-1 1:0.1 2:0.5 9:0.1",
                   "+1 1:0.6 2:0.2 8:0.2",
                   "-1 1:0.1 2:0.6 8:0.3",
                   "+1 1:0.4 2:0.7 9:0.4",
               ]
```

So the feature IDs are not sequential e.g. `1,2,3,` and nor are they globally unique e.g. `0.1` in the third line is given featureID of `1`, but when `0.1` appears in the first row, it is given featureID of `9`.

**Comment by dhruvghulati-zz** [comment]
I think figured this out. I use a `CountVectorizer` completely the same one I used for my multinomial logistic comparison, so each `featureID` is the ID of the word in the vocabulary, and the `featureVal` is the number of times that feature appears in the sentence. Note, the features are non-sparse, as for each sentence there are values for the 5000 features in the vocabulary.  A mapping of feature to featureID is:

`{u'gdp': 10, u'waralgeria': 40, u'had~-dep+had~dobj': 14, u'growth~prep_of+percent~num': 13, u'among': 1, u'civil': 6, u'rrb': 35,..}`

And I use:

`vectorizer = CountVectorizer(analyzer="word",token_pattern="[\S]+",stop_words=None,tokenizer=None,preprocessor=None,max_features=5000)`

Note, however, this makes training AROW **extremely** slow. 

Would AROW work if I made things sparse (i.e. only show features per sentence if their value is > 0)?

**Comment by andreasvlachos** [comment]
Assuming you are talking about constructing the `featureVector` used [here](https://github.com/andreasvlachos/arow_csc/blob/master/arow.py#L533), it should be used as sparse vector (i.e. only mention non-zero features) which is why the sparse vector library is used in the first place. If it is unclear how to use this sparse vector library, have a look at the README file accompanying the [library](http://web.engr.oregonstate.edu/~huanlian/software/hvector-1.0.tar.bz).

**Comment by dhruvghulati-zz** [comment]
OK brilliant, because I had to define new functions to take in words from a list that are in a different format to the current format you set up for your `arow_tests`, my function is still using `mydefaultdict`, with a check to only add in features with a value more than 0 (more than 0 occurrences of the token). So for example, if a 5000 long feature vector for a sentence has no occurrences for the word "mindful", the dict `"mindful":0` doesn't go into the `featureVector` (just an example, "mindful" would be replaced by the vocabulary token ID for the word mindful, e.g. 4211). :

```
def train_instance_from_list(costDict, featureList):
    """
    Generate an Instance from a set of training instances with costs. The input is a list of features e.g. words, vectorized. Note, the vectorizer is the only way of mapping each word to a unique ID.
    """
    featureVector = mydefaultdict(mydouble)

    for featureID,featureVal in enumerate(featureList):
        # This makes word features sparse
        if featureVal!=0:
            featureVector[featureID] = featureVal

    return Instance(featureVector, costDict)
```
